MEDIA_INTENT = 'media'

FEELING_INTENTS = ['smalltalk.appraisal.good', 'smalltalk.user.can_not_sleep',
                   'smalltalk.appraisal.thank_you', 'smalltalk.user.good',
                   'smalltalk.user.happy', 'smalltalk.user.sad',
                   'smalltalk.appraisal.bad', 'smalltalk.agent.happy',
                   'smalltalk.user.sick']

AFFIRMATION_INTENTS = ['yes', 'correct', 'smalltalk.dialog.correct',
                       'smalltalk.agent.right', 'smalltalk.appraisal.good']

NEGATION_INTENTS = ['no', 'wrong', 'smalltalk.dialog.wrong', 'skip',
                    'smalltalk.agent.wrong', 'smalltalk.dialog.wrong', 'smalltalk.appraisal.bad', 'repeat']

SMALLTALK_INTENTS = [
    'who_are_you',
    'tell_a_joke',
    'smalltalk.user.will_be_back',
    'smalltalk.agent.be_clever',
    'smalltalk.user.looks_like',
    'smalltalk.user.sick',
    'smalltalk.user.joking',
    'smalltalk.greetings.nice_to_talk_to_you',
    'smalltalk.agent.marry_user',
    'smalltalk.agent.talk_to_me',
    'smalltalk.user.has_birthday',
    'smalltalk.user.wants_to_see_agent_again',
    'smalltalk.user.happy',
    'smalltalk.greetings.whatsup',
    'smalltalk.agent.acquaintance',
    'smalltalk.greetings.goodnight',
    'smalltalk.user.lonely',
    'smalltalk.emotions.wow',
    'smalltalk.appraisal.bad',
    'smalltalk.agent.funny',
    'smalltalk.agent.birth_date',
    'smalltalk.agent.occupation',
    'smalltalk.appraisal.no_problem',
    'smalltalk.agent.age',
    'smalltalk.user.going_to_bed',
    'smalltalk.user.bored',
    'smalltalk.agent.bad',
    'smalltalk.user.misses_agent',
    'smalltalk.agent.beautiful',
    'smalltalk.user.testing_agent',
    'smalltalk.appraisal.good',
    'smalltalk.agent.there',
    'smalltalk.agent.annoying',
    'smalltalk.user.angry',
    'smalltalk.agent.busy',
    'smalltalk.dialog.sorry',
    'smalltalk.agent.right',
    'smalltalk.appraisal.welcome',
    'smalltalk.agent.suck',
    'smalltalk.agent.happy',
    'smalltalk.user.busy',
    'smalltalk.user.excited',
    'smalltalk.appraisal.well_done',
    'smalltalk.agent.hobby',
    'smalltalk.agent.family',
    'smalltalk.agent.clever',
    'smalltalk.agent.ready',
    'smalltalk.greetings.nice_to_see_you',
    'smalltalk.dialog.i_do_not_care',
    'smalltalk.user.wants_to_talk',
    'smalltalk.greetings.how_are_you',
    'smalltalk.agent.sure',
    'smalltalk.emotions.ha_ha',
    'smalltalk.agent.my_friend',
    'smalltalk.user.waits',
    'smalltalk.agent.real',
    'smalltalk.appraisal.thank_you',
    'smalltalk.dialog.what_do_you_mean',
    'smalltalk.user.back',
    'smalltalk.agent.origin',
    'smalltalk.agent.good',
    'smalltalk.agent.drunk',
    'smalltalk.agent.chatbot',
    'smalltalk.dialog.hug',
    'smalltalk.user.does_not_want_to_talk',
    'smalltalk.greetings.start',
    'smalltalk.user.sleepy',
    'smalltalk.user.tired',
    'smalltalk.greetings.nice_to_meet_you',
    'smalltalk.greetings.goodevening',
    'smalltalk.agent.answer_my_question',
    'smalltalk.user.sad',
    'smalltalk.agent.boss',
    'smalltalk.agent.can_you_help',
    'smalltalk.agent.crazy',
    'smalltalk.user.likes_agent',
    'smalltalk.agent.residence',
    'smalltalk.user.can_not_sleep',
    'smalltalk.agent.fired',
    'smalltalk.agent.date_user',
    'smalltalk.agent.hungry',
    'smalltalk.agent.boring',
    'smalltalk.dialog.hold_on',
    'smalltalk.user.good',
    'smalltalk.greetings.goodmorning',
    'smalltalk.user.needs_advice',
    'smalltalk.user.loves_agent',
    'smalltalk.user.here',
    'smalltalk.agent.make_sandwich'
]

ASTONISHED_AMAZED = ['astonished_interest', 'smalltalk.user.wow']
REQUEST_HELP = ['smalltalk.agent.can_you_help', 'clarify']

START = ['start',
         'hello',
         'smalltalk.greetings'
         'smalltalk.greetings.whatsup',
         'smalltalk.greetings.nice_to_see_you',
         'smalltalk.greetings.start',
         'smalltalk.greetings.goodevening',
         'smalltalk.greetings.goodmorning',
         'smalltalk.greetings.hello',
         ]
